### ISSUE TITLE
System preference under battery section

### ISSUE THREAD

**Issue by ameenjuz** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#9] opened 2021-01-01 00:58 UTC
i m using macOS Big Sur 11 i have strange problem in system preference under Battrey section
when i plug USB flash drive then (put hard disk to sleep when possible) tick box is reappear which can you look attached screenshot
![Screen Shot 2020-12-08 at 2 53 24 AM](https://user-images.githubusercontent.com/21066935/103431662-e0bc5e00-4be4-11eb-95c1-17c3b0b2b2b9.jpg)
when i ﻿unplug USB flash drive then (put ha﻿rd disk to sleep when possible) tick box is disap﻿pear which can you look attached﻿ screenshot
![Screen Shot 2020-12-08 at 3 01 30 AM](https://user-images.githubusercontent.com/21066935/103431665-f762b500-4be4-11eb-87fb-f91ee38c5766.jpg)
this is strange behavior in system preference under battery section which i m facing  

i mapped my all usbports correctly i don't know idea what is this issue and i boot my system using my internal EFI Partition
when i boot my system with external usb flash drive then (put hard disk to sleep when possible) tick box is reappear
i need help about this behavoir
another issue have your released v1.1.5 that is when i put to sleep then do not wake laptop by pressing power bottun once 
waking up by pressing twice
please consider this issue on Big Sur 11.1
i m using same laptop as you have Lenovo Ideapad 320-14IKB

**Comment by Ab2774** [comment] 2021-01-01 01:15
Hi @ameenjuz, Happy new year!
I don't actually know what's causing the first issue as I'm not facing it at all, it can be missing files inside macOS, it can be an unwanted app, I recommend you to install a new copy of macOS on an external hard drive and retest it.
For the second-click-to-wake-from-sleep issue, I have tried so many solutions and nothing seemed to work except osy's [USBWakeFixup](https://github.com/osy/USBWakeFixup), but the problem is that it will break 0x6d sleep causing an instant wake making SSDT-GPRW useless, it seems like this issue cannot be fixed in Big Sur, can you please attach a copy of your EFI alongside with a copy of IOREG, can you confirm that it was working on your EFI?
Thanks

**Comment by ameenjuz** [comment] 2021-01-02 06:13
@Ab2774 
i m using your released v1.1.5  same issue mentioned above
i m not able to dual boot windows with your EFI i mean windows 10 do not boot
and i m able to dual boot windows&macOS nicely smoothly with my patched DSDT but nothing boot windows 10 with your Hotpacth SSDTs

**Comment by ameenjuz** [comment] 2021-01-02 07:17
@Ab2774 <For the second-click-to-wake-from-sleep issue, I have tried so many solutions and nothing seemed to work except osy's USBWakeFixup, but the problem is that it will break 0x6d sleep causing an instant wake making SSDT-GPRW useless, it seems like this issue cannot be fixed in Big Sur> 
but clover have not this issue  i get wake up my laptop from sleep by pressing power button once in clover bootloader
i attached my clover EFI  check&use it why opencore have this issue 
[Clover-EFI.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/5759884/Clover-EFI.zip)

**Comment by Ab2774** [comment] 2021-01-02 15:23
Hmmm, that sounds strange, my explanation is that Clover automatically patches some frimware bugs and OpenCore does not, such as keyboard wake (this issue) and power button, I'll investigate this more and see what I can do.
Can you please test 1.1.4 release and see how dual boot is going? As since OC 0.6.4, Acidanthera made some big changes to dual booting, please leave your feedback as soon as you can so that I can fix this issue and not wait till the next release.
Cheers

**Comment by ameenjuz** [comment] 2021-01-02 20:22
@Ab2774 
i tested already 1.1.4 version do not boot windows 10 as a dual boot

**Comment by Ab2774** [comment] 2021-01-03 00:26
> @Ab2774
> i tested already 1.1.4 version do not boot windows 10 as a dual boot

Thanks for your report, I'll see what I can do and fix this issue as soon as I can, hope you can find a solution for your issue as well.
Regards

**Comment by Ab2774** [comment] 2021-03-07 15:06
https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/issues/12#issuecomment-792293345

**Closed as completed by Ab2774** 2021-03-07 15:06 UTC
Labels: bug
